name: Backup PostgreSQL

on:
  schedule:
    - cron: '0 0 * * 1'  # Toda segunda-feira às 00:00 UTC
  workflow_dispatch:       # Permite execução manual

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client rclone

      - name: Configurar Rclone
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf

      - name: Executar Backup
        env:
          PG_HOST: dpg-cugf0can91rc73d68lmg-a.oregon-postgres.render.com
          PG_DATABASE: greenmakerlab
          PG_USER: greenmakerlab_user
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Tentando conectar ao banco de dados..."
          BACKUP_FILE="backup_$(date +'%Y-%m-%d_%H-%M-%S').dump"
          pg_dump -Fc -h $PG_HOST -U $PG_USER -d $PG_DATABASE -f $BACKUP_FILE

          if [ $? -eq 0 ]; then
            echo "Conexão bem-sucedida!"
          else
            echo "Erro na conexão. Verifique host, usuário, senha e permissões."
            exit 1
          fi

          echo "Compactando o backup..."
          tar -czvf "$BACKUP_FILE.tar.gz" "$BACKUP_FILE"

          if [ $? -eq 0 ]; then
            echo "Backup compactado com sucesso!"
          else
            echo "Erro ao compactar o backup."
            exit 1
          fi

      - name: Enviar para o Google Drive
        run: |
          echo "Enviando backup para o Google Drive..."
          rclone copy "$BACKUP_FILE.tar.gz" backupDrive:Backups --log-file=backup_log.txt --log-level DEBUG
          cat backup_log.txt  # Exibe o log no console

          if [ $? -eq 0 ]; then
            echo "Backup enviado com sucesso!"
          else
            echo "Erro ao enviar o backup para o Google Drive."
            exit 1
          fi
      - name: Limpar arquivos locais
        run: |
          echo "Limpando arquivos locais..."
          rm -rf "$BACKUP_FILE"*